name: "VBAOR Deploy to EKS"

on:
 
  push:
    branches: [ stage, main ]
    paths: [ terraform/** ]
  pull_request:
    branches:
        - stage
    paths: 
        - terraform/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  AWS_REGION: us-east-1
  EKS_CLUSTER: vbo24-eks
  AWS_REGION: us-east-1

jobs:
  
  terraform:
    name: "Apply tf code chg"
    
    runs-on: ubuntu-latest
    defaults:
        run: 
            shell: bash
            working-directory: ./terraform

    steps:

    - name: Checkout source code
      id: commit
      uses: actions/checkout@v4

    - name: Setup Terraform with specified version
      uses: actions/checkout@v2
    
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

    - name: Terraform format
      id: fmt
      run: terraform fmt -check

    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan -no-color -input=false -out planfile
      continue-on-error: true

    - name: Terraform plan status
      if: steps.plan.outcome == 'failure'
      run: exit 1